"""Inject the annotated carrier-board figure (pins + legend) into index.html and boat.html.

Source data: media/v3-carrier-callouts.json (x, y are fractions of media/v3-carrier-top.* ).
Run:  python -I tools/gen_callouts.py   (re-run after editing the JSON or the DETAIL overrides)
The figure is written between <!-- BOARD:START --> and <!-- BOARD:END --> markers in each page.
"""
import json, re, sys
from pathlib import Path
from html import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from typo import tidy  # noqa: E402

SITE = Path(__file__).resolve().parents[1]
data = json.loads((SITE / "media" / "v3-carrier-callouts.json").read_text(encoding="utf-8"))

# Site-specific wording (V3 doesn't use the winch; the hardware stays for later sampling)
DETAIL = {
    "power-in": "Two XT60 connectors take separate battery packs: one for the electronics, and one for the winch used in the later sample-collection stage. A 5 V buck regulator on the underside powers the Pi and Teensy.",
    "power-monitors": "Two INA228 chips with shunt resistors measure voltage and current on the electronics pack and the winch pack.",
    "winch-kill": "A P-channel MOSFET switches power to the winch controller and fails safe: if the Teensy resets or loses power, the winch is off. Kept on the board for the later sample-collection stage.",
}


def pin(i, c):
    x, y = c["x"], c["y"]
    cls = ["pin"]
    if x > 0.72: cls.append("r")
    elif x < 0.28: cls.append("l")
    if y < 0.3: cls.append("b")
    detail = DETAIL.get(c["id"], c["detail"])
    return (f'<li class="{" ".join(cls)}" style="--x:{x:.4f};--y:{y:.4f}">'
            f'<button type="button" aria-expanded="false" aria-label="{i}: {escape(c["label"])}" aria-describedby="tip-{c["id"]}">{i}</button>'
            f'<span class="tip" id="tip-{c["id"]}" role="tooltip"><strong>{escape(c["label"])}</strong>{escape(detail)}</span></li>')


def figure(with_legend):
    """The annotated board. With a legend (boat page), the figure and its key sit side by side in .board-layout."""
    pins = "".join(pin(i + 1, c) for i, c in enumerate(data))
    fig = (
        '      <figure class="annotated reveal">\n'
        '        <div class="board-top">\n'
        '          <picture><source type="image/webp" srcset="media/v3-carrier-top.webp"><img src="media/v3-carrier-top.png" alt="Top view of the D.R.E.A.M.S V3 carrier board, rev D, with numbered callouts" width="1800" height="1399" loading="lazy"></picture>\n'
        f'          <ol class="pins" aria-label="Board callouts">{pins}</ol>\n'
        '        </div>\n'
        '        <figcaption class="label board-cap">V3 carrier board · rev D · top view · tap a number</figcaption>\n'
        '      </figure>')
    if with_legend:
        fig = "\n".join("  " + line for line in fig.split("\n"))
        items = "".join(f'<li><b>{i + 1:02d}</b><span><strong>{escape(c["label"])}</strong> {escape(DETAIL.get(c["id"], c["detail"]))}</span></li>'
                        for i, c in enumerate(data))
        fig = ('      <div class="board-layout">\n'
               f'{fig}\n'
               '        <div class="board-key reveal">\n'
               '          <p class="label">Key</p>\n'
               f'          <ol class="legend legend-full" aria-label="Key to the board callouts">{items}</ol>\n'
               '        </div>\n'
               '      </div>')
    return ('<!-- BOARD:START (generated by tools/gen_callouts.py) -->\n'
            f'{fig}\n'
            '      <!-- BOARD:END -->')


for page, legend in (("index.html", False), ("boat.html", True)):
    p = SITE / page
    t = p.read_text(encoding="utf-8")
    if "<!-- BOARD:START" in t:
        block = tidy(figure(legend))
        t = re.sub(r"<!-- BOARD:START.*?<!-- BOARD:END -->", lambda m: block, t, flags=re.S)
    else:
        # first run: replace the placeholder figure
        t, n = re.subn(r'<figure class="annotated reveal"[^>]*>.*?</figure>', figure(legend), t, count=1, flags=re.S)
        assert n == 1, page
    p.write_text(t, encoding="utf-8", newline="\n")
    print(page, "updated")
